### ISSUE TITLE
Exception: java.lang.NoClassDefFoundError: Could not initialize class com.intellij.lang.jsgraphql.schema.GraphQLSchemaProviderImpl

### ISSUE THREAD

**Issue by cmygray** [JetBrains/js-graphql-intellij-plugin#529]
### Stacktrace
Please paste the full stacktrace from the IDEA error popup.

```
java.lang.NoClassDefFoundError: Could not initialize class com.intellij.lang.jsgraphql.schema.GraphQLSchemaProviderImpl
	at jdk.internal.reflect.GeneratedConstructorAccessor129.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:877)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:48)
	at com.intellij.serviceContainer.ServiceComponentAdapter.access$createAndInitialize(ServiceComponentAdapter.kt:12)
	at com.intellij.serviceContainer.ServiceComponentAdapter$doCreateInstance$1.run(ServiceComponentAdapter.kt:42)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeNonCancelableSection(CoreProgressManager.java:223)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:590)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:573)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:27)
	at com.intellij.lang.jsgraphql.schema.GraphQLSchemaProvider.getInstance(GraphQLSchemaProvider.java:33)
	at com.intellij.lang.jsgraphql.psi.impl.GraphQLFragmentDefinitionMixin.getTypeScope(GraphQLFragmentDefinitionMixin.java:26)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLReferenceService.resolveFieldReference(GraphQLReferenceService.java:244)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLReferenceService.innerResolveReference(GraphQLReferenceService.java:95)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLReferenceService.doResolveReference(GraphQLReferenceService.java:87)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLCachingReference.resolveInner(GraphQLCachingReference.java:42)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLCachingReference$MyResolver.resolve(GraphQLCachingReference.java:56)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLCachingReference$MyResolver.resolve(GraphQLCachingReference.java:51)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$resolve$1(ResolveCache.java:154)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.lambda$loggingResolver$4(ResolveCache.java:260)
	at com.intellij.openapi.util.Computable.get(Computable.java:18)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:238)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolve(ResolveCache.java:154)
	at com.intellij.psi.impl.source.resolve.ResolveCache.resolveWithCaching(ResolveCache.java:289)
	at com.intellij.lang.jsgraphql.ide.resolve.GraphQLCachingReference.resolve(GraphQLCachingReference.java:37)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:177)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:165)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:204)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:248)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:227)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:292)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:174)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:135)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:40)
	at com.i...
```

### Version and Environment Details
Operation system: macOS 12.0.1
IDE version: IU-212.4746.92
Plugin version: 3.1.0

**Comment by RedShift1** [comment]
Same on
Operating system: Windows 10 Pro
IDE version: IU-221.5787.30
Plugin version: 3.1.4

**Comment by piotrd** [comment]
It also occurs in Linux (Ubuntu 22.04)

**Comment by hambro** [comment]
Same here:
Operating system: macOS 12.6
IDE version: PY-222.4345.23, built on October 10, 2022
Plugin version: 3.3.0
