### ISSUE TITLE
latest plugin won't install on 2022.2 EAP

### ISSUE THREAD

**Issue by yogurtearl** [JetBrains/js-graphql-intellij-plugin#608]
**Describe the bug**

Intellij 2022.2 EAP installs version 2.5.0 on this plugin, which doesn't work. 

The compatibility range for 2.5.0 was 182.711+ , so new EAPs pick up that version (which won't work)

**To Reproduce**
Try to install and use this plugin on latest 2022.2 EAP 

**Expected behavior**

Latest version (3.1+)  of this plugin installed

**Screenshots**
<img width="539" alt="image" src="https://user-images.githubusercontent.com/1195562/171034792-40625082-e836-421b-b448-d9da9ca73471.png">

<img width="791" alt="image" src="https://user-images.githubusercontent.com/1195562/171034783-304e6bd7-c5a6-4953-9574-bd20a97ee35a.png">

**Version and Environment Details**
IntelliJ IDEA 2022.2 EAP (Ultimate Edition)
Build #IU-222.2680.4, built on May 25, 2022

Runtime version: 17.0.3+7-b463.3 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
macOS 12.3.1
GC: G1 Young Generation, G1 Old Generation
Memory: 5128M
Cores: 10
Metal Rendering is ON

Kotlin: 222-1.6.21-release-357-IJ2680.4

**Comment by vepanimas** [comment]
Yep, I'm working on it already. Will prepare a new release ASAP.

**Comment by SimenB** [comment]
@vepanimas is this the issue to track when the plugin _is_ installed in the latest EAP but throws errors? Or should I file a separate issue?

E.g.

```
com.intellij.diagnostic.PluginException: Cannot load class com.intellij.lang.jsgraphql.ide.project.GraphQLPsiSearchHelper$1 (
  error: com/intellij/psi/impl/AnyPsiChangeListener$Adapter,
  classLoader=PluginClassLoader(plugin=PluginDescriptor(name=JS GraphQL, id=com.intellij.lang.jsgraphql, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.2680.4/IntelliJ IDEA 2022.2 EAP.app.plugins/JS GraphQL, version=2.5.0, package=null, isBundled=false), packagePrefix=null, instanceId=128, state=active)
)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:406)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:234)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:206)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at com.intellij.lang.jsgraphql.ide.project.GraphQLPsiSearchHelper.<init>(GraphQLPsiSearchHelper.java:112)
	at jdk.internal.reflect.GeneratedConstructorAccessor152.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:27)
	at com.intellij.lang.jsgraphql.ide.project.GraphQLPsiSearchHelper.getService(GraphQLPsiSearchHelper.java:86)
	at com.intellij.lang.jsgraphql.schema.SchemaIDLTypeDefinitionRegistry.<init>(SchemaIDLTypeDefinitionRegistry.java:77)
	at jdk.internal.reflect.GeneratedConstructorAccessor153.newInstance(Unknown Source)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstanceWithCaller(Constructor.java:499)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:480)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:52)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:890)
	at com.intellij.serviceContainer.ServiceComponentAdapter.createAndInitialize(ServiceComponentAdapter.kt:51)
	at com.intellij.serviceContainer.ServiceComponentAdapter.doCreateInstance(ServiceComponentAdapter.kt:41)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:119)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:73)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:66)
	at com.intellij.serviceContainer.ComponentManagerImpl.doGetService(ComponentManagerImpl.kt:609)
	at com.intellij.serviceContainer.ComponentManagerImpl.getService(ComponentManagerImpl.kt:583)
	at com.intellij.openapi.client.ClientAwareComponentManager.getFromSelfOrCurrentSession(ClientAwareComponentManager.kt:37)
	at com.intellij.openapi.client.ClientAwareComponentManager.getService(ClientAwareComponentManager.kt:22)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:27)
	at com.intellij.lang.jsgraphql.schema.SchemaIDLTypeDefinitionRegistry.getService(SchemaIDLTypeDefinitionRegistry.java:68)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getRegistryWithErrors$0(GraphQLTypeDefinitionRegistryServiceImpl.java:58)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getRegistryWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:57)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.lambda$getSchemaWithErrors$1(GraphQLTypeDefinitionRegistryServiceImpl.java:70)
	at java.base/java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1708)
	at com.intellij.lang.jsgraphql.schema.GraphQLTypeDefinitionRegistryServiceImpl.getSchemaWithErrors(GraphQLTypeDefinitionRegistryServiceImpl.java:69)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLConfigSchemaNode.<init>(GraphQLConfigSchemaNode.java:82)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasRootNode.getChildren(GraphQLSchemasRootNode.java:48)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$0(GraphQLSchemasPanel.java:128)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:915)
	at com.intellij.lang.jsgraphql.ide.project.schemastatus.GraphQLSchemasPanel.lambda$null$1(GraphQLSchemasPanel.java:125)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:297)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:539)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)
Caused by: java.lang.NoClassDefFoundError: com/intellij/psi/impl/AnyPsiChangeListener$Adapter
	at java.base/java.lang.ClassLoader.defineClass2(Native Method)
	at java.base/java.lang.ClassLoader.defineClass(ClassLoader.java:1103)
	at com.intellij.util.lang.UrlClassLoader.consumeClassData(UrlClassLoader.java:253)
	at com.intellij.util.lang.ZipResourceFile.findClass(ZipResourceFile.java:114)
	at com.intellij.util.lang.JarLoader.findClass(JarLoader.java:63)
	at com.intellij.util.lang.ClassPath.findClassInLoader(ClassPath.java:246)
	at com.intellij.util.lang.ClassPath.findClass(ClassPath.java:179)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:398)
	... 60 more
Caused by: java.lang.ClassNotFoundException: com.intellij.psi.impl.AnyPsiChangeListener$Adapter PluginClassLoader(plugin=PluginDescriptor(name=JS GraphQL, id=com.intellij.lang.jsgraphql, descriptorPath=plugin.xml, path=~/Library/Application Support/JetBrains/Toolbox/apps/IDEA-U/ch-0/222.2680.4/IntelliJ IDEA 2022.2 EAP.app.plugins/JS GraphQL, version=2.5.0, package=null, isBundled=false), packagePrefix=null, instanceId=128, state=active)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:209)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	... 68 more
```

**Comment by vepanimas** [comment]
2.5.0 was released 2 years ago, so there is no chance that it will work with the latest IDEA 😄 I restricted the upper version for the old plugin uploads so they won't be installed automatically anymore. 

Also, the release for the latest IDEA is also uploaded (3.1.4) and should be available in the Marketplace already. Hope it works as expected 🤞.

**Comment by jorrit** [comment]
Is there any way you could pull 2.5.0 and earlier versions from the marketplace? Every time a new IDEA version is released, the GraphQL plugin self-downgrades instead of being disabled temporarily because of version incompatibilities, like other plugins.

Anyway, thanks for your continued effort for this plugin!

**Comment by vepanimas** [comment]
@jorrit yep, you always can download and install any version from the marketplace manually (see a screenshot). Also, now it won't be downgraded anymore to 2.5.0, we specified an explicit version range for the old releases.

![install](https://user-images.githubusercontent.com/10243762/171614268-85349765-591d-4e61-b434-67a9b9bbb905.png)

**Comment by SimenB** [comment]
Can confirm 3.1.4 works great, thanks! The fixed upper bound on the old version is great as well, I was quite confused 😅
